name: CustomBreakTimeExample
main: NgLamVN\Example\Loader
version: 0.0.1
api: 4.0.0
depend: CustomBreakTimeAPI

commands:
  givetestitem:
    permission: give.test.item

permissions:
  give.test.item:
    default: op